from __future__ import annotations

from pathlib import Path

import click


@click.command("adapt")
@click.option("--platform", type=click.Choice(["claude-code", "codex", "copilot", "generic"]), required=True)
def cli(platform: str) -> None:
    project = Path.cwd()
    if platform == "codex":
        target = project / ".codex" / "instructions.md"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text("# AgentFlow Codex Instructions\n\nGenerated by runtime-adapters plugin.\n", encoding="utf-8")
    elif platform == "copilot":
        target = project / ".github" / "copilot" / "instructions.md"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text("# AgentFlow Copilot Instructions\n\nGenerated by runtime-adapters plugin.\n", encoding="utf-8")
    elif platform == "generic":
        target = project / ".agent-flow" / "prompts" / "system-prompt.md"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text("# AgentFlow System Prompt\n\nGenerated by runtime-adapters plugin.\n", encoding="utf-8")
    else:
        target = Path.home() / ".claude" / "rules" / "agent-flow-runtime.md"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text("# AgentFlow Claude Runtime Rules\n\nGenerated by runtime-adapters plugin.\n", encoding="utf-8")
    click.echo(f"Adapted for {platform}: {target}")
