from __future__ import annotations

from pathlib import Path

import click

from agent_flow.core.runtime import diagnose_runtime, format_runtime_status


@click.command("adapt")
@click.option("--platform", type=click.Choice(["claude-code", "codex", "copilot", "generic"]), required=True)
@click.option("--explain-runtime", is_flag=True, help="Show runtime diagnosis after adaptation.")
def cli(platform: str, explain_runtime: bool) -> None:
    """Adapt agent-flow for a specific platform and show runtime status."""
    project = Path.cwd()

    if platform == "claude-code":
        from agent_flow.core.claude_settings import ensure_project_claude_hooks

        settings_path, added = ensure_project_claude_hooks(project)
        target = settings_path
        click.echo(f"Adapted for claude-code: {settings_path} (added {added} hooks)")
    elif platform == "codex":
        target = project / ".codex" / "instructions.md"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text("# AgentFlow Codex Instructions\n\nGenerated by runtime-adapters plugin.\n", encoding="utf-8")
        click.echo(f"Adapted for codex: {target}")
    elif platform == "copilot":
        target = project / ".github" / "copilot" / "instructions.md"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text("# AgentFlow Copilot Instructions\n\nGenerated by runtime-adapters plugin.\n", encoding="utf-8")
        click.echo(f"Adapted for copilot: {target}")
    elif platform == "generic":
        target = project / ".agent-flow" / "prompts" / "system-prompt.md"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text("# AgentFlow System Prompt\n\nGenerated by runtime-adapters plugin.\n", encoding="utf-8")
        click.echo(f"Adapted for generic: {target}")

    if explain_runtime:
        diagnosis = diagnose_runtime(project)
        for line in format_runtime_status(diagnosis):
            click.echo(line)
